require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/support/shared_*/**/*.rb'
    - 'azeroth.gemspec'

RSpec/NestedGroups:
  Max: 4

RSpec/AlignLeftLetBrace:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
