version: '3'
services:
  base: &base
    image: azeroth
    working_dir: /home/app/app
    volumes:
      - .:/home/app/app

  base_build:
    <<: *base
    build: .
    command: echo done

  azeroth:
    <<: *base
    container_name: azeroth
    depends_on: [base_build]
    command: /bin/bash -c 'rspec'

  test_all:
    <<: *base
    depends_on: [base_build]
    command: /bin/bash -c 'rspec && yard && rake yardstick_measure && rake verify_measurements'

  circleci:
    image: azeroth_circleci
    build:
      context: ./
      dockerfile: Dockerfile.circleci
    volumes:
      - .:/home/circleci/project
