ignore:
  - lib/azeroth/decorator/class_methods.rb
  - lib/azeroth/decorator/options.rb
  - lib/azeroth/resourceable/class_methods.rb
  - lib/azeroth/resourceable.rb
  - lib/azeroth/version.rb
  - lib/azeroth/options.rb
  - lib/azeroth.rb
  - lib/azeroth/exception.rb
