threshold: 96.5
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - Azeroth::DummyDecorator#as_json
  ReturnTag:
    enabled: true
    exclude: []
  Summary::Presence:
    enabled: true
    exclude:
      - Azeroth::Decorator#initialize
      - Azeroth::Decorator::HashBuilder#initialize
      - Azeroth::Decorator::KeyValueExtractor#initialize
      - Azeroth::DummyDecorator#initialize
      - Azeroth::Exception::InvalidOptions#initialize
      - Azeroth::Model#initialize
      - Azeroth::Options#initialize
      - Azeroth::RequestHandler#initialize
      - Azeroth::ResourceBuilder#initialize
      - Azeroth::ResourceRouteBuilder#initialize
      - Azeroth::Resourceable::Builder#initialize
      - Azeroth::RoutesBuilder#initialize
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
